version: "3.8"

services:
  app:
    image: node:19-alpine3.15
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    command: node src/index.js
    restart: always
    networks:
      - db-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user2022
      MONGO_INITDB_ROOT_PASSWORD: user_password
    volumes:
      - .docker/db:/data/db
    restart: always
    networks:
      - db-net
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user2022
      ME_CONFIG_MONGODB_ADMINPASSWORD: user_password
      ME_CONFIG_MONGODB_URL: mongodb://user2022:user_password@mongo:27017/
    networks:
      - db-net
    depends_on:
      - mongo

networks:
  db-net:
